cols=['Avg_Cust_Waiting_Time',
 'Avg_Agent_Wating_Time',
 'Avg_Time_To_Reply_After_Assignment',
 'Duration',
 'Avg_Time_To_Solution',
 'Max_Cust_Waiting_Time',
 'Min_Cust_Waiting_Time',
 'Max_Time_To_Reply_After_Assignment',
 'Min_Time_To_Reply_After_Assignment',
 'Max_Agent_Wating_Time',
 'Max_Duration',
 'Min_Duration',
 'Max_Solution_Time',
 'Min_Solution_Time',
 'statistics.time_to_admin_reply',
 'statistics.time_to_first_close',
 'statistics.time_to_last_close',
 'statistics.median_time_to_reply',
'ticket_nps',
 'New_Rating',
 'irt',
 'sentiment','Cust_Happy_after_Solution','x0_Appointment',
 'x0_Billing',
 'x0_Business Intelligence',
 'x0_Business Management',
 'x0_Marketing & Sales',
 'x0_Misc',
 'x0_Mobile Application',
 'x0_Payment']
num_cols=['Avg_Cust_Waiting_Time',
 'Avg_Agent_Wating_Time',
 'Avg_Time_To_Reply_After_Assignment',
 'Duration',
 'Avg_Time_To_Solution',
 'Max_Cust_Waiting_Time',
 'Min_Cust_Waiting_Time',
 'Max_Time_To_Reply_After_Assignment',
 'Min_Time_To_Reply_After_Assignment',
 'Max_Agent_Wating_Time',
 'Max_Duration',
 'Min_Duration',
 'Max_Solution_Time',
 'Min_Solution_Time',
 'statistics.time_to_admin_reply',
 'statistics.time_to_first_close',
 'statistics.time_to_last_close',
 'statistics.median_time_to_reply','irt','ticket_nps']